CREATE TABLE IF NOT EXISTS PHERF.PHERF_PROD_TEST_UNSALTED (
    TENANT_ID CHAR(15) NOT NULL,
    CREATED_DATE DATE NOT NULL,
    FIELD VARCHAR,
    DATA_TYPE VARCHAR,
    OLDVAL_STRING VARCHAR,
    NEWVAL_STRING VARCHAR,
    DIVISION INTEGER,
    CONNECTION_ID VARCHAR   
    CONSTRAINT PK PRIMARY KEY 
    (
        TENANT_ID,
        CREATED_DATE DESC,
    )
) VERSIONS=1,MULTI_TENANT=true
