CREATE TABLE IF NOT EXISTS PHERF.PHERF_PROD_TEST_UNSALTED (
    ORGANIZATION_ID CHAR(15) NOT NULL,
    PARENT_ID CHAR(15) NOT NULL,
    CREATED_DATE DATE NOT NULL,
    ENTITY_HISTORY_ID CHAR(15) NOT NULL,
    FIELD_HISTORY_ARCHIVE_ID CHAR(15), 
    CREATED_BY_ID VARCHAR,                 
    FIELD VARCHAR,
    DATA_TYPE VARCHAR,
    OLDVAL_STRING VARCHAR,
    NEWVAL_STRING VARCHAR,
    OLDVAL_FIRST_NAME VARCHAR,
    NEWVAL_FIRST_NAME VARCHAR,
    OLDVAL_LAST_NAME VARCHAR,
    NEWVAL_LAST_NAME VARCHAR,
    OLDVAL_NUMBER DECIMAL,
    NEWVAL_NUMBER DECIMAL,
    OLDVAL_DATE DATE,
    NEWVAL_DATE DATE,
    ARCHIVE_PARENT_TYPE VARCHAR,
    ARCHIVE_FIELD_NAME VARCHAR,
    ARCHIVE_TIMESTAMP DATE,
    ARCHIVE_PARENT_NAME VARCHAR,
    DIVISION INTEGER, 
    CONNECTION_ID VARCHAR   
    CONSTRAINT PK PRIMARY KEY 
    (
        ORGANIZATION_ID, 
        PARENT_ID,
        CREATED_DATE DESC,
        ENTITY_HISTORY_ID
    )
) VERSIONS=1,MULTI_TENANT=true
