CREATE TABLE IF NOT EXISTS ABC (ORGANIZATION_ID CHAR(15) NOT NULL, NETWORK_ID CHAR(15) NOT NULL, CONSTRAINT PK PRIMARY KEY (ORGANIZATION_ID)) VERSIONS=1,MULTI_TENANT=true,REPLICATION_SCOPE=1;
ALTER TABLE ABC SET DISABLE_BACKUP=TRUE;
ALTER TABLE ABC SET "phoenix.max.lookback.age.seconds"=0;
ALTER TABLE ABC SET UPDATE_CACHE_FREQUENCY=172800000;