CREATE TABLE IF NOT EXISTS PHERF.TEST_TABLE (
    TENANT_ID CHAR(15) NOT NULL,
    PARENT_ID CHAR(15) NOT NULL,
    CREATED_DATE DATE NOT NULL,
    FIELD VARCHAR,
    OLDVAL_STRING VARCHAR,
    NEWVAL_STRING VARCHAR,
    SOME_INT INTEGER
    CONSTRAINT PK PRIMARY KEY
    (
        TENANT_ID,
        PARENT_ID,
        CREATED_DATE DESC
    )
) VERSIONS=1,MULTI_TENANT=true,SALT_BUCKETS=16
