sudo: required

language: python

services:
- docker

os: linux
dist: trusty

matrix:
  include:
  - env: PYENV=2.7.14 IMAGE=python:2.7.14-slim-stretch
  - env: PYENV=3.3.7 IMAGE=ubuntu:16.04
  - env: PYENV=3.4.7 IMAGE=ubuntu:16.04
  - env: PYENV=3.5.4 IMAGE=ubuntu:16.04
  - env: PYENV=3.6.3 IMAGE=python:3.6.3-slim-stretch

install:
- pip install coveralls # Need to have coveralls installed locally for after_success to run

script:
- >
  docker run
  -v $(pwd):$(pwd)
  -w $(pwd)
  -e PYENV=$PYENV
  -e IMAGE=$IMAGE
  -e KERBEROS_USERNAME=administrator
  -e KERBEROS_PASSWORD=Password01
  -e KERBEROS_REALM=example.com
  $IMAGE
  /bin/bash .travis.sh

after_success:
- coveralls
