CREATE TABLE IF NOT EXISTS PHERF.USER_DEFINED_TEST (
    TENANT_ID CHAR(15) NOT NULL,
    CREATED_DATE DATE NOT NULL,
    VAL_STRING VARCHAR
    CONSTRAINT PK PRIMARY KEY
    (
        TENANT_ID,
        CREATED_DATE DESC
    )
) VERSIONS=1,MULTI_TENANT=true,SALT_BUCKETS=16
