# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM apache/yetus:0.12.0

#####
# Update SpotBugs
#####
RUN rm -rf /opt/spotbugs \
    && git clone https://github.com/stoty/spotbugs.git \
    && cd spotbugs \
    && git checkout PHOENIX-1161-backport \
    && ./gradlew clean build -x test \
    && mkdir /opt/spotbugs \
    && tar -C /opt/spotbugs --strip-components 1 -xpf spotbugs/build/distributions/spotbugs-4.1.2.tgz \
    && chmod a+rx /opt/spotbugs/bin/* \
    && cd .. \
    && rm -rf ./spotbugs
ENV SPOTBUGS_HOME /opt/spotbugs
#####
# Enable spotbugs prefix for maven
#####
RUN sed -i -e 's/<\/pluginGroups>/<pluginGroup>com.github.spotbugs<\/pluginGroup><\/pluginGroups>/' /etc/maven/settings.xml
