# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM apache/yetus:0.13.0

#####
# Update SpotBugs
#####
RUN rm -rf /opt/spotbugs \
    && git clone https://github.com/stoty/spotbugs.git \
    && cd spotbugs \
    && git checkout PHOENIX-1161-backport \
    && ./gradlew clean build -x test \
    && mkdir /opt/spotbugs \
    && tar -C /opt/spotbugs --strip-components 1 -xpf spotbugs/build/distributions/spotbugs-4.1.2.tgz \
    && chmod a+rx /opt/spotbugs/bin/* \
    && cd .. \
    && rm -rf ./spotbugs
ENV SPOTBUGS_HOME /opt/spotbugs
#####
# Enable spotbugs prefix for maven
#####
RUN sed -i -e 's/<\/pluginGroups>/<pluginGroup>com.github.spotbugs<\/pluginGroup><\/pluginGroups>/' /etc/maven/settings.xml
#####
# /run/user directory for gpg
#####
RUN mkdir -p /run/user/910/gnupg/ \
    && chmod -R 700 /run/user/910 \
    && chown -R 910:910 /run/user/910 \
    && mkdir -p /var/run/user/910/gnupg \
    && chown -R 910:910 /var/run/user/910 \
    && chmod -R 700 /var/run/user/910
#####
# Update Java 11 packages to 11.0.11 (to avoid Java 11.0.9.1 version Jetty bug)
#####
RUN apt-get update \
    && apt-get -q install --no-install-recommends -y openjdk-11-jdk-headless=11.0.11+9-0ubuntu2~20.04 openjdk-11-jre-headless=11.0.11+9-0ubuntu2~20.04 openjdk-11-jre=11.0.11+9-0ubuntu2~20.04 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
#####
# Set default JDK to 11
#####
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
